services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: ecommerce_client
    ports: 
      - 5173:80
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
    env_file: 
      - .env
    volumes: 
      - .:/app
      - /app/node_modules
    networks:
      - ecommerce_network
    restart: always

networks:
  ecommerce_network:
    external: true